version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_PINECONE_API_KEY=${VITE_PINECONE_API_KEY}
      - VITE_PINECONE_ENVIRONMENT=${VITE_PINECONE_ENVIRONMENT}
      - VITE_AZURE_CLIENT_ID=${VITE_AZURE_CLIENT_ID}
      - VITE_AZURE_TENANT_ID=${VITE_AZURE_TENANT_ID}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped